name: Test DVC Setup


on:
    push:
      branches:
        - task-2
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dvc
      run: |
        python -m pip install --upgrade pip
        pip install dvc

    - name: Validate DVC status
      run: |
        dvc status